export const userListings = [
  {
    id: "eqp-001",
    name: "Mini Harvester",
    image: "/harvester.webp",
    pricePerDay: 5000,
    condition: "Good",
    model: "MH-2021",
    horsepower: "30HP",
    description: "Ideal for small-scale rice or maize harvesting.",
    securityDeposit: 10000,
    location: "Ogbakiri, Rivers",
    availability: "Available",
    ratings: 4.5,
    createdAt: "2025-07-15",
  },
  {
    id: "eqp-002",
    name: "Knapsack Sprayer",
    image: "/sprayer.webp",
    pricePerDay: 1200,
    condition: "Like New",
    model: "KS-Pro X",
    horsepower: "Manual",
    description: "20-liter capacity for pesticides and herbicide application.",
    securityDeposit: 3000,
    location: "Choba, Rivers",
    availability: "In Use",
    ratings: 4.8,
    createdAt: "2025-07-10",
  },
  {
    id: "eqp-003",
    name: "Soil Tiller Machine",
    image: "/tiller.webp",
    pricePerDay: 3500,
    condition: "Fair",
    model: "T-Compact 500",
    horsepower: "18HP",
    description: "Efficient for breaking and tilling dry, hard soil.",
    securityDeposit: 7000,
    location: "Omoku, Rivers",
    availability: "Available",
    ratings: 3.9,
    createdAt: "2025-07-05",
  },
];


export const userOrders = [
  {
    id: "order-001",
    equipmentName: "Mini Harvester",
    image: "/harvester.webp",
    startDate: "2025-07-20",
    endDate: "2025-07-22",
    duration: 3,
    totalPrice: 15000,
    status: "Approved",
    deliveryFee: 2000,
    deposit: 10000,
    renterName: "Chinedu Okoro",
    location: "Aluu, Rivers",
  },
  {
    id: "order-002",
    equipmentName: "Knapsack Sprayer",
    image: "/sprayer.webp",
    startDate: "2025-07-23",
    endDate: "2025-07-25",
    duration: 3,
    totalPrice: 3600,
    status: "Pending",
    deliveryFee: 1000,
    deposit: 3000,
    renterName: "Ngozi Umeh",
    location: "Elele, Rivers",
  },
  {
    id: "order-003",
    equipmentName: "Soil Tiller Machine",
    image: "/tiller.webp",
    startDate: "2025-07-10",
    endDate: "2025-07-11",
    duration: 2,
    totalPrice: 7000,
    status: "Completed",
    deliveryFee: 1500,
    deposit: 7000,
    renterName: "Samuel Etim",
    location: "Bori, Rivers",
  },
];
