export const tools = [
  {
   id: "1",
   toolType: "Drone",
   images: ["/tools/drone-2.svg", "/tools/drone-3.svg"],
   description:
     "Professional agricultural drone with crop monitoring capabilities. Features multispectral imaging, precision spraying system, and GPS-guided autonomous flight for field mapping and targeted treatments.",
   make: "DJI",
   model: "Agras T40",
   year: 2023,
   horsepower: null,
   fuelType: "Electric",
   transmission: "Digital Flight Control",
   drivetype: "Aerial",
   condition: "Excellent",
   availability: "Available",
   pricing: {
     dailyRate: 250,
     weeklyRate: 1400,
     monthlyRate: 4800,
     secureDeposit: 1200,
   },
   distance: 8, // Distance in miles for local rentals
},
  {
    id: "2",
    toolType: "Tractor",
    images: ["/tools/tractor.svg", "https://picsum.photos/200/300"],
    description:
      "This tractor is a versatile and powerful machine, perfect for a variety of farming tasks. It features a robust engine, comfortable seating, and intuitive controls, making it easy to operate even for long hours. The tractor is well-maintained and ready to work, ensuring reliable performance on your farm.",
    make: "John Deere",
    model: "6120M",
    year: 2020,
    horsepower: 120,
    fuelType: "Diesel",
    transmission: "PowerQuad Plus",
    drivetype: "4WD",
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 150,
      weeklyRate: 900,
      monthlyRate: 3000,
      secureDeposit: 500,
    },
    distance: 2, // Distance in miles for local rentals
  },
  {
    id: "3",
    toolType: "Plough",
    images: ["/tools/plow.svg", "https://picsum.photos/200/300"],
    description:
      "Heavy-duty reversible plough ideal for breaking up tough soil and preparing the land for planting. Works well with medium to large tractors and ensures efficient tillage.",
    make: "Land Pride",
    model: "RP30",
    year: 2018,
    horsepower: null,
    fuelType: null,
    transmission: null,
    drivetype: null,
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 40,
      weeklyRate: 240,
      monthlyRate: 800,
      secureDeposit: 150,
    },
    distance: 10, // Distance in miles for local rentals
  },
  {
    id: "4",
    toolType: "Combine Harvester",
    images: ["/tools/harvester.svg", "https://picsum.photos/200/300"],
    description:
      "This combine harvester offers excellent grain quality and low fuel consumption. Equipped with GPS guidance and auto-steer for efficient and stress-free harvesting.",
    make: "Case IH",
    model: "Axial-Flow 7150",
    year: 2021,
    horsepower: 375,
    fuelType: "Diesel",
    transmission: "Hydrostatic",
    drivetype: "2WD",
    condition: "Like New",
    availability: "Available",
    pricing: {
      dailyRate: 450,
      weeklyRate: 2700,
      monthlyRate: 8500,
      secureDeposit: 1200,
    },
    distance: 8, // Distance in miles for local rentals
  },
  {
    id: "5",
    toolType: "Sprayer",
    images: ["/tools/sprayer.svg", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    description:
      "High-capacity mounted sprayer suitable for large-scale pesticide and fertilizer application. Features include a durable boom, adjustable nozzles, and a corrosion-resistant tank.",
    make: "Hardi",
    model: "Navigator 4000",
    year: 2019,
    horsepower: null,
    fuelType: null,
    transmission: null,
    drivetype: null,
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 70,
      weeklyRate: 420,
      monthlyRate: 1400,
      secureDeposit: 300,
    },
    distance: 5, // Distance in miles for local rentals
  },
  {
    id: "6",
    toolType: "Manure Spreader",
    images: ["/tools/manure-spreader.svg", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    description:
      "Efficient rotary tiller perfect for seedbed preparation and weed control. Lightweight yet powerful, suitable for tractors with lower horsepower.",
    make: "Shaktiman",
    model: "Regular Light",
    year: 2022,
    horsepower: null,
    fuelType: null,
    transmission: null,
    drivetype: null,
    condition: "New",
    availability: "Available",
    pricing: {
      dailyRate: 35,
      weeklyRate: 200,
      monthlyRate: 700,
      secureDeposit: 100,
    },
    distance: 3, // Distance in miles for local rentals
  },
  {
    id: "7",
    toolType: "Baler",
    images: ["/tools/balers.svg", "https://picsum.photos/200/300"],
    description:
      "Round baler designed for quick, dense baling of hay and straw. Easy to attach and operate, ensures high output with minimal manpower.",
    make: "New Holland",
    model: "BR7060",
    year: 2020,
    horsepower: 65,
    fuelType: "Diesel",
    transmission: "Mechanical",
    drivetype: "PTO Driven",
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 100,
      weeklyRate: 600,
      monthlyRate: 2000,
      secureDeposit: 400,
    },
    distance: 7, // Distance in miles for local rentals
  },
  {
    id: "8",
    toolType: "Seeder",
    images: ["/tools/seeder.svg", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    description:
      "Precision seed drill for uniform seed placement and reduced wastage. Enhances crop emergence and ensures optimal row spacing for increased yield.",
    make: "John Deere",
    model: "1590",
    year: 2021,
    horsepower: null,
    fuelType: null,
    transmission: null,
    drivetype: null,
    condition: "Like New",
    availability: "Available",
    pricing: {
      dailyRate: 85,
      weeklyRate: 500,
      monthlyRate: 1600,
      secureDeposit: 350,
    },
    distance: 19, // Distance in miles for local rentals
  },
  {
    id: "9",
    toolType: "Forage Harvester",
    images: ["/tools/forage-harvester.svg", "https://picsum.photos/200/300"],
    description:
      "High-pressure diesel-powered irrigation pump ideal for large farmlands. Delivers consistent water flow and is easy to transport.",
    make: "Honda",
    model: "WB30XT",
    year: 2019,
    horsepower: 6.5,
    fuelType: "Petrol",
    transmission: "Manual Start",
    drivetype: "Portable",
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 40,
      weeklyRate: 240,
      monthlyRate: 800,
      secureDeposit: 150,
    },
    distance: 10, // Distance in miles for local rentals
  },
  {
    id: "10",
    toolType: "Grain Cart",
    images: ["/tools/grain-cart.svg", "https://picsum.photos/200/300"],
    description:
      "Heavy-duty disc harrow built for land leveling and breaking up tough clods. Durable steel frame and easily adjustable cutting angles.",
    make: "Mahindra",
    model: "DH 13",
    year: 2020,
    horsepower: null,
    fuelType: null,
    transmission: null,
    drivetype: null,
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 50,
      weeklyRate: 300,
      monthlyRate: 1000,
      secureDeposit: 200,
    },
    distance: 2, // Distance in miles for local rentals
  },
  {
    id: "11",
    toolType: "Auger",
    images: ["/tools/auger.svg", "https://picsum.photos/200/300"],
    description:
      "Compact and fuel-efficient power tiller suited for small to mid-sized farms. Features ergonomic controls and superior soil pulverizing capacity.",
    make: "Kubota",
    model: "KCT-90",
    year: 2022,
    horsepower: 9,
    fuelType: "Diesel",
    transmission: "Gear Drive",
    drivetype: "2WD",
    condition: "New",
    availability: "Available",
    pricing: {
      dailyRate: 55,
      weeklyRate: 320,
      monthlyRate: 1100,
      secureDeposit: 250,
    },
    distance: 4, // Distance in miles for local rentals
  },
  {
    id: "12",
    toolType: "Cultivator",
    images: ["/tools/cultivator.svg", "https://picsum.photos/200/300"],
    description:
      "Efficient PTO-driven manure spreader with even distribution and corrosion-resistant build. Ideal for organic farms and large-scale composting.",
    make: "Frontier",
    model: "MS1112",
    year: 2018,
    horsepower: 50,
    fuelType: "PTO",
    transmission: null,
    drivetype: "Tow Behind",
    condition: "Used",
    availability: "Available",
    pricing: {
      dailyRate: 60,
      weeklyRate: 360,
      monthlyRate: 1200,
      secureDeposit: 300,
    },
    distance: 8, // Distance in miles for local rentals
  },
  {
    id: "13",
    toolType: "Harrow",
    images: ["/tools/harrow.svg", "https://picsum.photos/200/300", "https://picsum.photos/200/300"],
    description:
      "Mobile grain dryer for efficient post-harvest processing. Reduces grain moisture quickly and safely, preserving quality during storage.",
    make: "Alvan Blanch",
    model: "DFT5000",
    year: 2021,
    horsepower: null,
    fuelType: "Diesel",
    transmission: "Electric Control",
    drivetype: "Stationary",
    condition: "Like New",
    availability: "Available",
    pricing: {
      dailyRate: 130,
      weeklyRate: 750,
      monthlyRate: 2500,
      secureDeposit: 600,
    },
    distance: 3, // Distance in miles for local rentals
  },
];
